// Eastern League records exported from Meet Manager (tag "Eastern Open") on 2026-09-25. Only field events have Eastern League records in that file.
// Western League records are not in that file yet - add them under West when exported.
window.LEAGUE_RECORDS = {
 "East": [
  {
   "gender": "Girl",
   "age_low": 9,
   "age_high": 10,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.3208,
   "mark_text": "4-04",
   "holder": "Campbell Perry",
   "team": "West Valley",
   "rec_year": 2023
  },
  {
   "gender": "Boy",
   "age_low": 9,
   "age_high": 10,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.2192,
   "mark_text": "4-00",
   "holder": "Andrew Taylor",
   "team": "Chatsworth Chiefs",
   "rec_year": 2002
  },
  {
   "gender": "Girl",
   "age_low": 11,
   "age_high": 12,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.27,
   "mark_text": "4-02",
   "holder": "Michelle Pattison",
   "team": "Northridge Pacers",
   "rec_year": 2001
  },
  {
   "gender": "Boy",
   "age_low": 11,
   "age_high": 12,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.3462,
   "mark_text": "4-05",
   "holder": "Josh Vulich",
   "team": "Northridge Pacers",
   "rec_year": 1995
  },
  {
   "gender": "Girl",
   "age_low": 13,
   "age_high": 14,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.397,
   "mark_text": "4-07",
   "holder": "Mary Perdew",
   "team": "Running Warriors",
   "rec_year": 2002
  },
  {
   "gender": "Boy",
   "age_low": 13,
   "age_high": 14,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.5748,
   "mark_text": "5-02",
   "holder": "Jesse Pacheco",
   "team": "Pacers",
   "rec_year": 2005
  },
  {
   "gender": "Girl",
   "age_low": 15,
   "age_high": 18,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.2192,
   "mark_text": "4-00",
   "holder": "Brette Lavery",
   "team": "Pacers",
   "rec_year": 1994
  },
  {
   "gender": "Boy",
   "age_low": 15,
   "age_high": 18,
   "event_code": "HJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 1.4478,
   "mark_text": "4-09",
   "holder": "Dayne Crist",
   "team": "Raiders",
   "rec_year": 2004
  },
  {
   "gender": "Girl",
   "age_low": 5,
   "age_high": 6,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 2.3368,
   "mark_text": "7-08",
   "holder": "Alaya Robinson",
   "team": "Antelope",
   "rec_year": 2024
  },
  {
   "gender": "Boy",
   "age_low": 5,
   "age_high": 6,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 2.667,
   "mark_text": "8-09",
   "holder": "Aryian Shackelford",
   "team": "Eagles",
   "rec_year": 2018
  },
  {
   "gender": "Girl",
   "age_low": 7,
   "age_high": 8,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 2.8893,
   "mark_text": "9-05.75",
   "holder": "Alexandra Garcia",
   "team": "Eagles",
   "rec_year": 2016
  },
  {
   "gender": "Boy",
   "age_low": 7,
   "age_high": 8,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 3.2512,
   "mark_text": "10-08",
   "holder": "Darius Dorsey",
   "team": "Eagles",
   "rec_year": 2005
  },
  {
   "gender": "Girl",
   "age_low": 9,
   "age_high": 10,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 3.6004,
   "mark_text": "11-09.75",
   "holder": "Lia Farrior",
   "team": "Eagles",
   "rec_year": 2024
  },
  {
   "gender": "Boy",
   "age_low": 9,
   "age_high": 10,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 3.9243,
   "mark_text": "12-10.50",
   "holder": "Scott Sistilli",
   "team": "Running Warriors",
   "rec_year": 1995
  },
  {
   "gender": "Girl",
   "age_low": 11,
   "age_high": 12,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 3.9624,
   "mark_text": "13-00",
   "holder": "Cynea Casidsid",
   "team": "Eagles",
   "rec_year": 2005
  },
  {
   "gender": "Boy",
   "age_low": 11,
   "age_high": 12,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 4.5402,
   "mark_text": "14-10.75",
   "holder": "Corbett Mcdaniel",
   "team": "Sonics",
   "rec_year": 2016
  },
  {
   "gender": "Girl",
   "age_low": 13,
   "age_high": 14,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 7.5184,
   "mark_text": "24-08",
   "holder": "Yasmin Rosas",
   "team": "Eagles",
   "rec_year": 2019
  },
  {
   "gender": "Boy",
   "age_low": 13,
   "age_high": 14,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 8.9916,
   "mark_text": "29-06",
   "holder": "Brian Thornton",
   "team": "Supersonics",
   "rec_year": 2019
  },
  {
   "gender": "Girl",
   "age_low": 15,
   "age_high": 18,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 3.9814,
   "mark_text": "13-00.75",
   "holder": "Crystal Florez",
   "team": "Pacers",
   "rec_year": 2009
  },
  {
   "gender": "Boy",
   "age_low": 15,
   "age_high": 18,
   "event_code": "LJ",
   "is_relay": false,
   "is_time": false,
   "mark_value": 4.9149,
   "mark_text": "16-01.50",
   "holder": "Anthony Castro",
   "team": "Falcons",
   "rec_year": 1995
  },
  {
   "gender": "Girl",
   "age_low": 9,
   "age_high": 10,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 6.1214,
   "mark_text": "20-01",
   "holder": "Na'sira Tyus",
   "team": "Antelope Valley",
   "rec_year": 2019
  },
  {
   "gender": "Boy",
   "age_low": 9,
   "age_high": 10,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 6.7564,
   "mark_text": "22-02",
   "holder": "Jordan Banks",
   "team": "Reseda Cowboys",
   "rec_year": 2010
  },
  {
   "gender": "Girl",
   "age_low": 11,
   "age_high": 12,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 8.3312,
   "mark_text": "27-04",
   "holder": "Shawnique Willliams",
   "team": "Hawks",
   "rec_year": 2002
  },
  {
   "gender": "Boy",
   "age_low": 11,
   "age_high": 12,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 8.5598,
   "mark_text": "28-01",
   "holder": "Dino Beatty",
   "team": "Northridge Pacers",
   "rec_year": 2011
  },
  {
   "gender": "Girl",
   "age_low": 13,
   "age_high": 14,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 7.8105,
   "mark_text": "25-07.50",
   "holder": "Toni Grisby",
   "team": "Antelope Valley",
   "rec_year": 2005
  },
  {
   "gender": "Boy",
   "age_low": 13,
   "age_high": 14,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 9.4043,
   "mark_text": "30-10.25",
   "holder": "Adrian Guzman",
   "team": "West Valley",
   "rec_year": 2023
  },
  {
   "gender": "Girl",
   "age_low": 15,
   "age_high": 18,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 7.3977,
   "mark_text": "24-03.25",
   "holder": "Angela Kelly",
   "team": "Running Warriors",
   "rec_year": 2007
  },
  {
   "gender": "Boy",
   "age_low": 15,
   "age_high": 18,
   "event_code": "JT",
   "is_relay": false,
   "is_time": false,
   "mark_value": 10.3759,
   "mark_text": "34-00.50",
   "holder": "Frederick Erreguin-Garcia",
   "team": "Bears",
   "rec_year": 2014
  },
  {
   "gender": "Girl",
   "age_low": 7,
   "age_high": 8,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 8.382,
   "mark_text": "27-06",
   "holder": "Dylan Baldocchi",
   "team": "Eagles",
   "rec_year": 2024
  },
  {
   "gender": "Boy",
   "age_low": 7,
   "age_high": 8,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 10.8966,
   "mark_text": "35-09",
   "holder": "Jacob Morales",
   "team": "Golden Bears",
   "rec_year": 2024
  },
  {
   "gender": "Girl",
   "age_low": 9,
   "age_high": 10,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 10.668,
   "mark_text": "35-00",
   "holder": "Dylan Baldocchi",
   "team": "Eagles",
   "rec_year": 2005
  },
  {
   "gender": "Boy",
   "age_low": 9,
   "age_high": 10,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 19.7675,
   "mark_text": "64-10.25",
   "holder": "Anders Ribeiro",
   "team": "Pacers",
   "rec_year": 2005
  },
  {
   "gender": "Girl",
   "age_low": 11,
   "age_high": 12,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 11.6967,
   "mark_text": "38-04.50",
   "holder": "Lorelai Pierce",
   "team": "Raiders",
   "rec_year": 2005
  },
  {
   "gender": "Boy",
   "age_low": 11,
   "age_high": 12,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 15.875,
   "mark_text": "52-01",
   "holder": "Judah Ybarra",
   "team": "Warriors",
   "rec_year": 2005
  },
  {
   "gender": "Girl",
   "age_low": 13,
   "age_high": 14,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 15.6718,
   "mark_text": "51-05",
   "holder": "Cymphany Brown",
   "team": "Pacers",
   "rec_year": 2024
  },
  {
   "gender": "Boy",
   "age_low": 13,
   "age_high": 14,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 15.748,
   "mark_text": "51-08",
   "holder": "Daniel Nunez",
   "team": "Golden Bears",
   "rec_year": 2024
  },
  {
   "gender": "Boy",
   "age_low": 15,
   "age_high": 18,
   "event_code": "SP",
   "is_relay": false,
   "is_time": false,
   "mark_value": 21.5138,
   "mark_text": "70-07",
   "holder": "Micah Russell",
   "team": "Warriors",
   "rec_year": 2005
  }
 ],
 "West": []
};
